### ISSUE TITLE
Tracking Issue: Project Rewrite and Improvement

### ISSUE THREAD

**Issue by dfireBird** [dfireBird/tincan#1]
Tracking issue for the complete refactoring and rewrite of the project

- [ ] Code Rewrite and Refactoring
	- [x] Rewrite widgets as a `struct` (Finished with #2)
		- [x] Message Box
		- [x] Input Box
		- [x] Static Text Widget 
	- [x] Rewrite the Network
	- [ ] Rewrite the State (UI)
	- [x] Implement Protocol message as struct and use serializer to convert to bytes to send it over network 
- [ ] UX Improvement
	- [ ] Dialog widget
	- [ ] Prompt the user before connecting
	- [ ] Prompt the user before file transfer
